# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protobufs/db.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
import protobufs.db_pb2


class DatabaseServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetBox(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.GetBoxRequest, protobufs.db_pb2.GetBoxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBoxes(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.GetAllBoxesRequest, protobufs.db_pb2.GetBoxesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CreateBox(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.CreateBoxRequest, protobufs.db_pb2.CreateBoxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateBox(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.UpdateBoxRequest, protobufs.db_pb2.UpdateBoxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteBox(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.DeleteBoxRequest, protobufs.db_pb2.DeleteBoxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBoxesInCategory(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.GetBoxesInCategoryRequest, protobufs.db_pb2.GetBoxesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBoxesInTimeRange(self, stream: 'grpclib.server.Stream[protobufs.db_pb2.GetBoxesInTimeRangeRequest, protobufs.db_pb2.GetBoxesResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/DatabaseService/GetBox': grpclib.const.Handler(
                self.GetBox,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.GetBoxRequest,
                protobufs.db_pb2.GetBoxResponse,
            ),
            '/DatabaseService/GetBoxes': grpclib.const.Handler(
                self.GetBoxes,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.GetAllBoxesRequest,
                protobufs.db_pb2.GetBoxesResponse,
            ),
            '/DatabaseService/CreateBox': grpclib.const.Handler(
                self.CreateBox,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.CreateBoxRequest,
                protobufs.db_pb2.CreateBoxResponse,
            ),
            '/DatabaseService/UpdateBox': grpclib.const.Handler(
                self.UpdateBox,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.UpdateBoxRequest,
                protobufs.db_pb2.UpdateBoxResponse,
            ),
            '/DatabaseService/DeleteBox': grpclib.const.Handler(
                self.DeleteBox,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.DeleteBoxRequest,
                protobufs.db_pb2.DeleteBoxResponse,
            ),
            '/DatabaseService/GetBoxesInCategory': grpclib.const.Handler(
                self.GetBoxesInCategory,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.GetBoxesInCategoryRequest,
                protobufs.db_pb2.GetBoxesResponse,
            ),
            '/DatabaseService/GetBoxesInTimeRange': grpclib.const.Handler(
                self.GetBoxesInTimeRange,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.db_pb2.GetBoxesInTimeRangeRequest,
                protobufs.db_pb2.GetBoxesResponse,
            ),
        }


class DatabaseServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetBox = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/GetBox',
            protobufs.db_pb2.GetBoxRequest,
            protobufs.db_pb2.GetBoxResponse,
        )
        self.GetBoxes = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/GetBoxes',
            protobufs.db_pb2.GetAllBoxesRequest,
            protobufs.db_pb2.GetBoxesResponse,
        )
        self.CreateBox = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/CreateBox',
            protobufs.db_pb2.CreateBoxRequest,
            protobufs.db_pb2.CreateBoxResponse,
        )
        self.UpdateBox = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/UpdateBox',
            protobufs.db_pb2.UpdateBoxRequest,
            protobufs.db_pb2.UpdateBoxResponse,
        )
        self.DeleteBox = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/DeleteBox',
            protobufs.db_pb2.DeleteBoxRequest,
            protobufs.db_pb2.DeleteBoxResponse,
        )
        self.GetBoxesInCategory = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/GetBoxesInCategory',
            protobufs.db_pb2.GetBoxesInCategoryRequest,
            protobufs.db_pb2.GetBoxesResponse,
        )
        self.GetBoxesInTimeRange = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DatabaseService/GetBoxesInTimeRange',
            protobufs.db_pb2.GetBoxesInTimeRangeRequest,
            protobufs.db_pb2.GetBoxesResponse,
        )
